### PR TITLE
set variables before checkout

### PR DESCRIPTION
**Pull request by kizdebski**
Can we move providing environment parameters before checkout? 
Some plugins like jenkins release plugin (my case) run in "Build Environment, not directly in "Build". Effect is that during releasing version variables are not generated yet. 
Moving variables generation before scm checkout solves such cases.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Likely addresses https://issues.jenkins-ci.org/browse/JENKINS-32532

**Comment by oleg-nenashev** [comment]
Pre-checkout does not actually cover all cases. E.g. if you use a Pre-SCM build step, the info won't be propagated there. Fix like https://github.com/oleg-nenashev/ownership-plugin/commit/9871283990bd76c8f04bb61cfdeb4a1c30159a4c should be a better solution

**Comment by fabiodcasilva** [comment]
> Pre-checkout does not actually cover all cases. E.g. if you use a Pre-SCM build step, the info won't be propagated there. Fix like [oleg-nenashev/ownership-plugin@9871283](https://github.com/oleg-nenashev/ownership-plugin/commit/9871283990bd76c8f04bb61cfdeb4a1c30159a4c) should be a better solution

@oleg-nenashev is your observation and suggestion still valid today?

@kizdebski are you still interested in this pull request?

Thanks!

**Comment by mmh891113** [comment]
Likely this issue: https://issues.jenkins-ci.org/browse/JENKINS-24277

**Comment by kizdebski** [comment]
@fabiodcasilva I'm interested. On newest version of plugin problem still exists.

**Comment by fabiodcasilva** [comment]
this is fixed by https://github.com/jenkinsci/build-user-vars-plugin/pull/24

**Pull request closed without merging**
