### PR TITLE
plugin do require 1.450, so no need to check if UserIdCause is supported

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
I suppose <code>USER_ID_CAUSE_CLASS_NAME</code> can be removed as well

**Comment by ndeloof** [comment]
indeed

**Comment by tfennelly** [comment]
:+1:

**Comment by stephenc** [comment]
:+1:

**Pull request merged**
