### PR TITLE
Refactor build user vars plugin: Remove unnecessary utility class, relocated constants to a more generic context

### PR DESCRIPTION
**Pull request by fabiodcasilva**
Refactor build user vars plugin: 
- Remove unnecessary utility class.
- Relocated constants to a more generic context class.
- Add missing tests to UsernameUtils

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by fabiodcasilva** [comment]
@basil can I kindly ask you for a review?

**Comment by fabiodcasilva** [comment]
@oleg-nenashev can you please review this PR?

**Review by basil — APPROVED** [review]
Sorry for the late reply. This looks great!

**Comment by fabiodcasilva** [comment]
> Sorry for the late reply. This looks great!

thanks!

**Pull request merged**
